---
title: "Figure 3 Extension"
author: "Matt Easton"
date: "4/6/2022"
output: pdf_document
---

# Improving Figure 3 #####

## Bring in the Data
```{r}
library(haven)
load(file = '/df_mtg.rda')
```


## Loading Relevant Libraries
```{r}
library(tidyverse)
library(car)
library(Hmisc)
library(kableExtra)
library(sessioninfo)
library(ggplot2)
```



## Important functions to find values
``` {r}
# First, two functions to get the results we need ####
m_se<-function(ts,ta){
  #INPUTS
   # ts: vector of variables of samples who seek out the treatment
   # ta: vector of variables of samples who avoid the treatment
  
  ## difference in means
  m_ts<-mean(ts,na.rm = TRUE)
  m_ta<-mean(ta,na.rm = TRUE)

  diff<-m_ts-m_ta

  ## the number of observations in each category 
  N1 <- length(na.omit(ts))
  N0 <- length(na.omit(ta))
  
  ## variances and standard error
  var1 <- sum((ts - m_ts)^2,na.rm=T) / (N1 - 1)
  var0 <- sum((ta - m_ta)^2,na.rm=T) / (N0 - 1)
  
  se <- sqrt(var1/N1 + var0/N0)
  
  ## Degree of Freedom calculation 
  df_numerator <- (var1/N1 + var0/N0)^2
  df_denominator <- (var1^2/(N1^2*(N1-1))) + (var0^2/(N0^2*(N0-1)))

  degrees_free <- df_numerator/df_denominator
  
  ll <- diff - qt(.95,degrees_free)*se
  ul <- diff + qt(.95,degrees_free)*se
  
  output<-(c(diff,ll,ul))
  return(output)}

#Note: ggplot can be stubborn about list order of variables, usually sticking to alphabetical ordering. As an "easy hack" to get around this, we are labeling our variables with the alphabet at the front to maintain the order we want (ie Female becomes I_Female)
gfun<-function(data_selector,data_avoider){
  I_Female<-m_se(data_selector$gender,data_avoider$gender)
  H_Non_White<-m_se(data_selector$non_white,data_avoider$non_white)
  G_Education<-m_se(data_selector$education,data_avoider$education)
  F_Income<-m_se(data_selector$income,data_avoider$income)
  E_PID<-m_se(data_selector$pid,data_avoider$pid)
  D_Ideology<-m_se(data_selector$ideo,data_avoider$ideo)
  C_MeToo<-m_se(data_selector$fam_movement,data_avoider$fam_movement)
  B_Specific<-m_se(data_selector$dv_pca_metoo,data_avoider$dv_pca_metoo)
  A_General<-m_se(data_selector$dv_pca_general,data_avoider$dv_pca_general)
  
  
  data<-rbind(I_Female,H_Non_White,G_Education,F_Income,E_PID,D_Ideology,C_MeToo,B_Specific,A_General) %>%
    as.data.frame() %>% 
    rownames_to_column(var = "Covariates")
  
  colnames(data)<-c("Covariates","Difference","Lower","Upper")
  
  return(data)
}

```


## Figure 3 Part 1: Overall
```{r}
#Figure 3 Part 1: Overall####
treatment_selector<-filter(df_mtg,balance=="Select Treatment")
treatment_avoider<-filter(df_mtg,balance=="Avoid Treatment")

data_1<-gfun(treatment_selector,treatment_avoider)

#Improve labels of y axis
y_labels <- c("Overall", "Specific Support", "MeToo Familiarity", "Ideology", "PID", "Income", "Education", "Non-white","Female")

figure3_Overall<-ggplot(data = data_1,aes(y=Covariates,x=Difference)) +
  geom_point(size=2) +
  geom_errorbar(aes(xmin=Lower,xmax=Upper), width = 0.2) +
  geom_vline(xintercept = 0, linetype="dotted") +
  scale_y_discrete(labels = y_labels) +
  xlim(-1.5, 1.5)+
  theme_bw()+
  theme(axis.text.x = element_text(size=15), axis.text.y = element_text(size=15)) +
  ggtitle("Overall") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.title = element_text(size = 20))

print(figure3_Overall)

ggsave("/Users/mattyeaston/Dropbox/Berkeley/Spring 2022/Methods 231B/figure3_Overall.pdf", width = 6, height = 10)

```

## Figure 2 Part 2: By Gender
```{r}
#Figure 3 Part 2: Gender ####
# gender analysis
f_df_mtg<-filter(df_mtg,gender==1)

treatment_selector<-filter(df_mtg,balance=="Select Treatment")
treatment_avoider<-filter(df_mtg,balance=="Avoid Treatment")

data_2_f<-gfun(treatment_selector,treatment_avoider)
data_2_f$gender<-"Female" %>% as.factor()

# male analysis
m_df_mtg<-filter(df_mtg,gender==0)

treatment_selector<-filter(m_df_mtg,balance=="Select Treatment")
treatment_avoider<-filter(m_df_mtg,balance=="Avoid Treatment")

data_2_m<-gfun(treatment_selector,treatment_avoider)
data_2_m$gender<-"Male" %>% as.factor()

# integrating
data_2<-rbind(data_2_f,data_2_m)

figure3_Gender <- ggplot(data = data_2,aes(y=Covariates,x=Difference))+
  geom_point(aes(shape = gender, colour=gender), size = 3,
             position=position_jitterdodge(jitter.width=0.01))+
  geom_errorbar(aes(xmin=Lower,xmax=Upper,colour=gender),
                width = 0.2,
                position=position_jitterdodge(jitter.width=0.01))+
  geom_vline(xintercept = 0, linetype="dotted")+
  scale_y_discrete(labels = y_labels) +
  xlim(-1.5, 1.5)+
  theme_bw() +
  theme(axis.text.x = element_text(size=15), axis.text.y = element_text(size=15)) +
  ggtitle("By Gender") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.title = element_text(size = 20)) +
  theme(axis.text.y = element_blank(),
  axis.ticks.y = element_blank(),
  axis.title.y = element_blank())+
  theme(legend.position="none")

print(figure3_Gender)

ggsave("/Users/mattyeaston/Dropbox/Berkeley/Spring 2022/Methods 231B/figure3_Gendernol.pdf", width = 6, height = 10)

```

## Figure 3 Part 3: By Partisanship
```{r}
#Figure 3 Part 3: Partisanship ####

# Republican analysis
R_df_mtg<-filter(df_mtg,Partisanship=="Republicans")

treatment_selector<-filter(R_df_mtg,balance=="Select Treatment")
treatment_avoider<-filter(R_df_mtg,balance=="Avoid Treatment")

data_3_r<-gfun(treatment_selector,treatment_avoider)
data_3_r$partisanship<-"Republicans" %>% as.factor()

# Democrat analysis
D_df_mtg<-filter(df_mtg,Partisanship=="Democrats")
treatment_selector<-filter(D_df_mtg,balance=="Select Treatment")
treatment_avoider<-filter(D_df_mtg,balance=="Avoid Treatment")

data_3_d<-gfun(treatment_selector,treatment_avoider)

data_3_d$partisanship<-"Democrats" %>% as.factor()

# integrating
data_3<-rbind(data_3_r,data_3_d)
party <- c("deepred", "deepblue")

figure3_Partisan <- ggplot(data = data_3,aes(y=Covariates,x=Difference))+
  geom_point(aes(shape = partisanship, colour=partisanship), size = 3,
             position=position_jitterdodge(jitter.width=0.01))+
  geom_errorbar(aes(xmin=Lower,xmax=Upper,colour=partisanship),
                width = 0.2,
                position=position_jitterdodge(jitter.width=0.01))+
  geom_vline(xintercept = 0, linetype="dotted")+
  scale_y_discrete(labels = y_labels) +
  xlim(-1.5, 1.5)+
  theme_bw() +
  theme(axis.text.x = element_text(size=15), axis.text.y = element_text(size=15)) +
  ggtitle("By Partisanship") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.title = element_text(size = 20)) +
  theme(axis.text.y = element_blank(),
  axis.ticks.y = element_blank(),
  axis.title.y = element_blank()) +
  theme(legend.position="none")

print(figure3_Partisan)

ggsave("/Users/mattyeaston/Dropbox/Berkeley/Spring 2022/Methods 231B/figure3_Partisanshipnol.pdf", width = 6, height = 10)
```

